### ISSUE TITLE
params are doubled

### ISSUE THREAD

**Issue by armins** [rs-dev/query-interface-client#16]
At least POST requests seem to double their params in a way like that:

```
params = { params, model_name => { params } }
```

Bndy debugged, could be at QueryInterface::Client::API.request

https://github.com/rs-dev/query-interface-client/blob/master/lib/query-interface-client/api.rb#L28

**Comment by armins** [comment]
thank you wrap_parameters.rb, not a query-interface-issue

**Comment by natano** [comment]
Thanks for investigating, @armins.
